name: drupalcaas
recipe: drupal10
config:
  webroot: web
  php: "8.1"
  via: nginx
  build:
    - composer install

# Tell Drush what URL we want.
tooling:
  drush:
    env:
      DRUSH_OPTIONS_URI: "https://drupalcaas.lndo.site"
