# Platform.sh app configuration.
# @see https://docs.platform.sh/configuration/app.html

name: 'app'
type: 'php:7.4'
runtime:
    extensions:
        - redis

relationships:
    database: 'db:mysql'
    redis: 'cache:redis'
    solr: 'solr:solr'

disk: 2048
mounts:
    '/web/sites/default/files':
        source: local
        source_path: 'files'
    '/tmp':
        source: local
        source_path: 'tmp'
    '/private':
        source: local
        source_path: 'private'
    '/.drush':
        source: local
        source_path: 'drush'
    '/drush-backups':
        source: local
        source_path: 'drush-backups'
    '/.console':
        source: local
        source_path: 'console'

build:
    flavor: composer

hooks:
    build: |
        set -e
    deploy: |
        set -e
        php ./drush/platformsh_generate_drush_yml.php
        cd web
        drush -y cache-rebuild
        drush -y updatedb
        drush -y config-import

web:
    locations:
        '/':
            root: 'web'
            expires: 5m
            passthru: '/index.php'
            allow: false
            rules:
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true

                '^/sites/sites\.php$':
                    scripts: false
                '^/sites/[^/]+/settings.*?\.php$':
                    scripts: false

        '/sites/default/files':
            allow: true
            expires: 5m
            passthru: '/index.php'
            root: 'web/sites/default/files'
            # Do not execute PHP scripts from the writeable mount.
            scripts: false
            rules:
                # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
                '^/sites/default/files/(css|js)':
                    expires: 2w

crons:
    drupal:
        spec: '*/19 * * * *'
        cmd: 'cd /app/web ; drush core-cron'
