services:
  mariadb:
    image: wodby/mariadb:10.11-3.26.3
    container_name: "drupalcaas_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  php:
    image: wodby/drupal-php:8.2-dev-4.47.2
    container_name: "drupalcaas_php"
    environment:
      FREE_AS_IN_SAUCE: true
      DRUSH_OPTIONS_URI: "http://drupalcaas.docker.localhost"
    volumes:
    - ./:/var/www/html:cached
  nginx:
    image: wodby/nginx:1.25-5.33.4
    container_name: "drupalcaas_nginx"
    depends_on:
    - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: drupal10
    volumes:
    - ./:/var/www/html:cached
    labels:
    - "traefik.http.routers.drupalcaas_nginx.rule=Host(`drupalcaas.docker.localhost`)"
  traefik:
    image: traefik:v2.0
    container_name: "drupalcaas_traefik"
    command: --api.insecure=true --providers.docker
    ports:
    - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
