name: drupalcaas
type: drupal10
docroot: web
php_version: "8.1"
webserver_type: nginx-fpm

# We're being picky about our settings.php setup, which means we also do Drush URL manually too.
disable_settings_management: true
web_environment:
- DRUSH_OPTIONS_URI=https://drupalcaas.ddev.site
